### ISSUE TITLE
schema fails when selecting columns from a really wide table

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaData/TableOperations.jl#20]
Hello
Due to a recent change in `Tables.jl` developers now need to also consider specializing on `Tables.Schema{nothing, nothing}` in addition to `Tables.Schema{names, types}`. see [here](https://github.com/JuliaData/Tables.jl/pull/241).
Users will eventually pop into this error when selecting a few columns from a really wide table as shown below.

```julia
julia> ncols = 1000000
1000000

julia> df = DataFrame(rand(6, ncols), :auto);

julia> n = TableOperations.select(df, :x1, :x2);

julia> Tables.schema(n);
ERROR: MethodError: no method matching columntype(::Nothing, ::Nothing, ::Symbol)
```

**Comment by OkonSamuel** [comment]
The following naive solution should do the trick. Maybe someone has a better fix?
```julia
function typesubset(sch::Tables.Schema{nothing, nothing}, nms::NTuple{N, Symbol}) where {N}
    names = sch.names
     types = sch.types
    return Tuple{Any[Tables.columntype(names, types, nm) for nm in nms]...}
end

function typesubset(sch::Tables.Schema{nothing, nothing}, inds::NTuple{N, Int}) where {N}
    types = sch.types
    return Tuple{Any[types[i] for i in inds]...}
end
typesubset(::Tables.Schema{nothing, nothing}, ::Tuple{}) = Tuple{}

namesubset(::Tables.Schema{nothing, nothing}, nms::NTuple{N, Symbol}) where {N} = nms
Base.@pure namesubset(::Tables.Schema{nothing, nothing}, inds::NTuple{N, Int}) where {N} = (names = sch.names; ntuple(i -> names[inds[i]], N))
namesubset(::Tables.Schema{nothing, nothing}, ::Tuple{}) = ()

```

**Comment by quinnj** [comment]
> Due to a recent change in `Tables.jl` developers now need to also consider specializing on `Tables.Schema{nothing, nothing}` in addition to `Tables.Schema{names, types}`. see [here](https://github.com/JuliaData/Tables.jl/pull/241).

It should be noted that the threshold where Tables.jl will switch to this alternative `Schema` representation is pretty high: 67_000 columns. This was chosen specifically because many operations on tables this wide were failing anyway; there are fundamental limits in the compiler right now that mean creating tuples/namedtuples that large start breaking in weird ways. 

Anyway, that aside, yes, we should fix the case here. I just wanted to clarify that this kind of operation didn't work before anyway.

**Comment by quinnj** [comment]
PR up: https://github.com/JuliaData/TableOperations.jl/pull/22
